### ISSUE TITLE
Deleting chats from Bürokratt

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Buerokratt-Chatbot#855]
AS AN Administrative User
I WANT TO be able to set up a automatic deletation for chats 
SO THAT Bürokratt does not keep chats longer than necessary  and according to GDPR

### Acceptance Criteria

- [x] New submenu item is created under "Haldus" and is called "Sõnumite kustutamine"
- [x] There are two categories of chats for deletion: 1) authenticated and 2) not authenticated
- [x] Possibility to set up two different deletion day counts regarding the selection of the chat type described in previous AC
- [ ] Possibility to set a single deletion day countdown that applies to both chat types (authenticated and not authenticated)
- [ ] Deletion day countdown criteria is max 4 digits, and if else, gives error message "Päevade maksimaalne valik saab olla kuni 9999".
- [x] Administrator can select exact automatic time of day for deletion (for example: 1AM)
- [ ] An option is available to view chats that will be deleted in a specified number of days. The number of days can be configured manually by choosing dates between period or selecting preadded selection: 1 päev (1 day), 7 päeva (7 days), 31 päeva (31 days) and 90 päeva (90 days). This will be based on the selection of selected period and "Kustutamise kellaeg"
- [ ] Total amount of chats that will be generated, as selected in previous AC, will be shown as a total number. Chats have to be in ENDED status and the count will have unique chats and does not take account messages inside it.
- [ ] Chats that will be deleted are shown below the settings board and are shown as in Historical Chats (Veslutsed -> Ajalugu) view. When clicking on the view (vaata) button, the view remains in the same window. List of chat will be based on the selection made in "Näita tulevikus aeguvaid sõnumeid"

Figma: https://www.figma.com/design/JYnmhsKixyUSCSUXXfwTAA/B%C3%BCrokratt?node-id=4662-24399&node-type=frame&t=gmAFIZYSrWBebjJ9-0 

#### Analytics data retention:

- [ ] #891

#### DSL

- [ ] Save deletion-related settings in a chatbot's database table called `configuration`
- [ ] Cronjob to fetch all chats that need to be deleted based on Backoffice's settings
- [x] #953
- [ ] #951
- [ ] #952
> [!NOTE]
> We will use this approach so that the current solution for the Analytics Module would remain intact
> Will refactor it in later stages

**Comment by rasmusei** [comment]
@turnerrainer please take a look at this task

**Comment by ffrose** [comment]
Seems like the functionality is working overall but not deleting the authenticated conversations. 
Tested with using the date 02.12.2024. Everything before that should be deleted.
![Image](https://github.com/user-attachments/assets/673aba22-9647-41dc-bee3-49559071c7f4)

**Comment by ExiRain** [comment]
After debugging it seems like flow still works  correctly, unremoved records had corrupted data in them.
Fixed minor styling, and added nonce to use.

Related PR's :
-  [CronManager](https://github.com/buerokratt/CronManager/pull/39)
- [Chatbot](https://github.com/buerokratt/Buerokratt-Chatbot/pull/1067)

**Comment by rasmusei** [comment]
Related task: https://github.com/buerokratt/Buerokratt-Chatbot/issues/1068

**Comment by RiinaLi** [comment]
Tested: 1) authenticated and 2) not authenticated both are working correctly.

**Comment by RiinaLi** [comment]
Tested since friday (07.02.2025), should have been deleted saturday 155 chats - still in the chat deleting list. Checked again yesterday, chats keep adding to the list, but nothing will be deleted as criteria says. For example old chats from 13.01.2025 should have been deleted already on 08.02.2025, when I changed criteria to 10 days, before it was 365 days.

![Image](https://github.com/user-attachments/assets/9c4acdf4-973a-422c-a747-9ad6e26bcf12)

**Comment by RiinaLi** [comment]
Tested several days, still not working. On 12.03.2025 should have been deleted following shats: 

![Image](https://github.com/user-attachments/assets/bc97184c-dedb-4227-ba19-8eaf5307b515) that are still in the list for 14.03.2025 delation: 

<img width="877" alt="Image" src="https://github.com/user-attachments/assets/d9c39321-9d4e-4ad3-977b-d9734e159ec2" />

**Comment by ExiRain** [comment]
Most of issues were due to deployment misconfigurations.
Second part was due to some conversations had more than one state (START / END). Originally every conversation have OPEN state when it start and ENDED when its ended, but some conversation have wrong data being started and ended multiple times.I did small change would need to test it.And in my opiniion this specific case should be fixed as separate task as of why they have more than one state.

https://github.com/buerokratt/Buerokratt-Chatbot/pull/1228

**Comment by rasmusei** [comment]
@1AhmedYasser added new AC about authentication information.

**Comment by straiker** [comment]
https://github.com/user-attachments/assets/49b358b4-0779-4404-823e-60504f754dd8

**Comment by reinik2** [comment]
AT Rejected:

1. Deleting conversations cannot be turned off. Error is displayed when both anonymous and authenticated conversation deletion is turned off and when page is reloaded, previous configuration is displayed.

<img width="1713" height="827" alt="Image" src="https://github.com/user-attachments/assets/6b8c3882-4891-4ea6-a5c8-2544d664a684" />

2. Conversation counter above the table showing conversations about to be deleted shows seemingly random numbers and does not reflect the number or rows in the table.

<img width="1698" height="416" alt="Image" src="https://github.com/user-attachments/assets/c0c9ebf0-b3af-4743-86e7-85da69a22707" />

3. Logic issues with date range fields. Start date field (left) only displays tomorrow's value and is not editable. End date field by default display's current date value (less than start date). This creates confusion on what is actually displayed in the table.

4. Deletion period specified can be both negative and exceed 9999 mentioned in the requirements:

<img width="1701" height="810" alt="Image" src="https://github.com/user-attachments/assets/2b716bea-6726-4392-91e7-f068b5c0a71c" />

5. Deletion time adds +1 hour after clicking save and reloading the page. Please see video above for demonstration.

**Comment by reinik2** [comment]
AT passed.

**Comment by ffrose** [comment]
Unable to load default settings 

https://github.com/buerokratt/Buerokratt-Chatbot/pull/1964 Change has been added.

<img width="1800" height="580" alt="Image" src="https://github.com/user-attachments/assets/6df5fd81-e7f1-44b5-ae6e-bcd32a723c90" />

**Comment by reinik2** [comment]
Stage passed.
